version: '3.8'

services:
  postgres_db:
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stores-transactions
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./backend/database/data/dev:/var/lib/postgresql/data
    container_name: postgres_db
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    networks:
      - webapp
      - database
    ports:
      - 5501:5501
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres_db:5432/stores-transactions
      - BACKEND_PORT=5501
    volumes:
      - ./backend/node_modules:/app/node_modules
      - ./backend/src:/app/src
    depends_on:
      - postgres_db
    restart: always
    command: bash -c "./wait-for-it.sh postgres_db:5432 -- npx prisma migrate dev && npm run prisma:seed && npm run start:dev"
    container_name: server
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_SERVICE_URL=http://server:5501
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - webapp
    ports:
      - 3000:3000
    command: npm run dev
    stdin_open: true
    restart: always
    container_name: web
networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
