name: Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "strs-transactions-manager-dev"
          heroku_email: "eniasoliveira27@gmail.com"
          stack: "container"
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          directory: backend/coverage/
          name: Generate Coverage Report # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
